### ISSUE TITLE
add better-sqlite3

### ISSUE THREAD

**Issue by robots4life** [ihaback/sveltekit-twitter-clone#2]
when visiting http://localhost:5173/signup error

```bash
Internal server error: Cannot find module 'better-sqlite3' imported from 'sveltekit-twitter-clone/src/routes/(auth)/signup/+page.server.ts'
```

is shown, fix it by adding `better-sqlite3` to dependencies

**Comment by ihaback** [comment]
Fixed in https://github.com/ihaback/sveltekit-twitter-clone/commit/60f33fcb4754a65a4423ca4b5990eda583e73af6
